# Generated by Django 2.1 on 2018-08-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPolicyRepo',
            fields=[
                ('term_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('term_type', models.CharField(max_length=50)),
                ('term_version', models.CharField(max_length=15)),
                ('term_html', models.TextField()),
                ('term_text', models.TextField()),
                ('term_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTermsRegistry',
            fields=[
                ('user_term_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer_external_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(db_column='term_id', on_delete=django.db.models.deletion.PROTECT, to='launchpad.TermsPolicyRepo')),
            ],
        ),
    ]
