# Generated by Django 2.1 on 2018-08-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termspolicyrepo',
            name='term_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertermsregistry',
            name='user_term_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
