# Generated by Django 2.1 on 2018-08-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0002_auto_20180811_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEligibilityRegistry',
            fields=[
                ('user_eligibility_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_external_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
