# Generated by Django 2.1 on 2018-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0003_usereligibilityregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereligibilityregistry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usertermsregistry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
