# Generated by Django 2.1 on 2018-08-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0004_auto_20180814_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenOrders',
            fields=[
                ('token_order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_external_id', models.CharField(max_length=64)),
                ('usd_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('token_value', models.DecimalField(decimal_places=18, max_digits=28)),
                ('payment_currency', models.CharField(max_length=10)),
                ('payment_currency_value', models.DecimalField(decimal_places=18, max_digits=28)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
