# Generated by Django 2.1 on 2018-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0005_tokenorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenorders',
            name='payment_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenorders',
            name='payment_destination_tag',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
