# Generated by Django 2.1 on 2018-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0006_auto_20180815_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenorders',
            name='payment_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenorders',
            name='payment_currency_value',
            field=models.DecimalField(decimal_places=18, max_digits=28, null=True),
        ),
    ]
