# Generated by Django 2.1 on 2018-08-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0007_auto_20180821_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenorders',
            name='confirms_needed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tokenorders',
            name='qrcode_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tokenorders',
            name='status_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tokenorders',
            name='txn_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
