# Generated by Django 2.1 on 2018-08-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0009_tokenorders_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenorders',
            name='token_order_external_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
