# Generated by Django 2.1 on 2018-08-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0010_tokenorders_token_order_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTransactions',
            fields=[
                ('token_transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_transaction_external_id', models.CharField(max_length=64)),
                ('customer_external_id', models.CharField(max_length=64)),
                ('transaction_type', models.CharField(max_length=25)),
                ('token_value', models.DecimalField(decimal_places=18, max_digits=28)),
                ('withdrawal_address', models.CharField(max_length=255, null=True)),
                ('txn_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-token_transaction_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='tokenorders',
            options={'ordering': ['-token_order_id']},
        ),
        migrations.AddField(
            model_name='tokenorders',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenorders',
            name='tokens_credited',
            field=models.BooleanField(default=False),
        ),
    ]
